#!/bin/sh
if [ "$1" == "" ] || [ "$2" == "" ]; then
    echo "RazorRun <list of input files> <analyzer name> <options>"
else
   cp ${CMSSW_BASE}/src/llp_analyzer/bin/Run$2 .
   echo $1 $2
    ./Run$2 $1 ${@:3}
    rm -rf Run$2
fi
